Mango.Web/Models/CouponDto.cs
namespace Mango.Web.Models
{
    public class CouponDto
    {
        public int CouponId { get; set; }
        public string CouponCode { get; set; }
        public double DiscountAmount { get; set; }
        public int MinAmount { get; set; }
    }
}

Mango.Web/Models/ErrorViewModel.cs
namespace Mango.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Mango.Web/Models/RequestDto.cs
using static Mango.Web.Utility.SD;

namespace Mango.Web.Models
{
    public class RequestDto
    {
        public ApiType ApiType { get; set; } = ApiType.GET;
        public string Url { get; set; }
        public object Data { get; set; }
        public string AccessToken { get; set; }

        public ContentType ContentType { get; set; } = ContentType.Json;
    }   
}

Mango.Web/Models/ResponseDto.cs
namespace Mango.Web.Models
{
    public class ResponseDto
    {
        //It validates the response any datatype
        public object? Result { get; set; }

        //If the request is success or not
        public bool IsSuccess { get; set; } = true;

        //It displayes error or success message
        public string Message { get; set; } = "";
    }
}

Mango.Web/Controllers/CouponController.cs
using Mango.Web.Models;
using Mango.Web.Service.IService;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Mango.Web.Controllers
{
    public class CouponController : Controller
    {
        private readonly ICouponService _couponService;
        public CouponController(ICouponService couponService)
        {
            _couponService = couponService;
        }
        public async Task<IActionResult> CouponIndex()
        {
            List<CouponDto>? list = null;

            ResponseDto? response = await _couponService.GetAllCouponAsync();

            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<CouponDto>>(Convert.ToString(response.Result));
            }
            else
            {
                TempData["error"] = response?.Message;
            }
            return View(list);
        }
        public async Task<IActionResult> CouponCreate()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CouponCreate(CouponDto model)
        {
            if (ModelState.IsValid)
            {
                ResponseDto? response = await _couponService.CreateCouponsAsync(model);

                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "Coupon created successfully";
                    return RedirectToAction(nameof(CouponIndex));
                }
                else
                {
                    TempData["error"] = response?.Message;
                }
            }
            return View(model);
        }
        public async Task<IActionResult> CouponDelete(int couponId)
        {
            ResponseDto? response = await _couponService.GetCouponByIdAsync(couponId);

            if (response != null && response.IsSuccess)
            {
                CouponDto? model = JsonConvert.DeserializeObject<CouponDto>(Convert.ToString(response.Result));
                return View(model);
            }
            else
            {
                TempData["error"] = response?.Message;
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> CouponDelete(CouponDto couponDto)
        {
            ResponseDto? response = await _couponService.DeleteCouponsAsync(couponDto.CouponId);

            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Coupon deleted successfully";
                return RedirectToAction(nameof(CouponIndex));
            }
            else
            {
                TempData["error"] = response?.Message;
            }
            return View(couponDto);
        }

    }
}

Mango.Web/Controllers/HomeController.cs
using Mango.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Mango.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Mango.Web/Views/Coupon/CouponCreate.cshtml
@model CouponDto

<form asp-action="CouponCreate">
    <br />
    <div class="container border p-3">
        <h1 class="text-white text-center">Create Coupon</h1>

        <hr />
        <div class="row">
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;"> Coupon Code</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="CouponCode" class="form-control" />
                <span asp-validation-for="CouponCode" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Discount Amount</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="DiscountAmount" class="form-control" />
                <span asp-validation-for="DiscountAmount" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Minimum Amount</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="MinAmount" class="form-control" />
                <span asp-validation-for="MinAmount" class="text-danger"></span>
            </div>

            <div class="col-5 offset-2">

                <a asp-action="CouponIndex" class="btn-primary btn form-control ">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Create" class="btn btn-success form-control" />

            </div>

        </div>

        <div>
        </div>
    </div>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Mango.Web/Views/Coupon/CouponDelete.cshtml
@model CouponDto

<form asp-action="CouponDelete">
    <br />
    <div class="container border p-3">
        <h1 class="text-white text-center">Delete Coupon</h1>
        <input asp-for="CouponId" hidden />
        <hr />
        <div class="row">
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;"> Coupon Code</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="CouponCode" disabled class="form-control" />
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Discount Amount</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="DiscountAmount" disabled class="form-control" />
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Minimum Amount</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="MinAmount" disabled class="form-control" />
            </div>

            <div class="col-5 offset-2">
                <a asp-action="CouponIndex" class="btn-primary btn form-control ">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Delete" class="btn btn-danger form-control" />
            </div>

        </div>

        <div>
        </div>
    </div>
</form>

Mango.Web/Views/Coupon/CouponIndex.cshtml
@model IEnumerable<CouponDto>

<div class="card shadow border-0 mt-4">
	<div class="card-header bg-secondary bg-gradient ml-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h1 class="text-white">Coupons List</h1>
			</div>
		</div>
	</div>
	<div class="card-body p-4">
		<div class="row pb-3">
			<div class="col-6">
			</div>
			<div class="col-6 text-end">
				<a asp-action="CouponCreate" class="btn btn-outline-primary"><i class="bi bi-plus-square"></i> Create New Coupon</a>

			</div>
		</div>
		<table class="table">
			<thead>
				<tr>
					<th>
						Coupon Code
					</th>
					<th>
						Discount Amount
					</th>
					<th>
						Minimum Amount
					</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				@foreach(var item in Model)
				{
				<tr>
					<td> @item.CouponCode
					</td>
					<td> @((item.DiscountAmount).ToString("c"))
					</td>
						<td>
							@((item.MinAmount).ToString("c"))
					</td>
									<td>
							<a asp-action="CouponDelete" asp-route-couponId="@item.CouponId" class="btn btn-danger">
							<i class="bi bi-trash"></i>
						</a>
					</td>
				</tr>
				}
			</tbody>
		</table>

	</div>

</div>

Mango.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Mango.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mango.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css"/>
    <link rel="stylesheet" href="~/Mango.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mango.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Content Management
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-controller="Coupon" asp-action="CouponIndex">Coupon</a></li>
                                <li><hr class="dropdown-divider"></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <partial name="_Notifications"/>
        </main>
    </div>

    <footer class="footer text-muted">
        <div class=text-center>
            Made with <i class="bi bi-heart-fill"></i> by Development!!
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Mango.Web/Views/Shared/_Notifications.cshtml
@if(TempData["error"]!=null){
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]')
        </script>
}
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}

@*Note - use <script type="text/javascript"> </script> don't use type/javascript*@